

''' CONDITIONAL Operator
       it will check the condition first, if condition is True
       it will execute logical True else it will execute
       logical False. Terinary operator

Other Languages:
      (condition)?Logical_True:Logical_False

In Python:
     Logical_True  if condition else Logical_False
'''
x,y=10,50
print("x is big") if x>y else print("y is big")

marks=54
print("Pass") if marks>34 else print("Fail")











